package capstone.documenttaggingsystem;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit test suite for verifying IdfLoader file parsing and edge-case error handling.
 */
public class IdfLoaderTest {

    /**
     * Loads the test IDF Map generated by the training utility and verifies
     * that the loaded map matches the expected values.
     */
    @Test
    public void testLoadingIdfMap() {
        IdfLoader idfLoader = new IdfLoader();

        Map<String, Double> expected = TestUtils.generateIdfMap();

        String idfPath = System.getProperty("user.dir") 
                + File.separator + "idfMaps" 
                + File.separator + "testIdfMap.txt";

        Map<String, Double> actual = idfLoader.loadMap(idfPath);

        Assertions.assertEquals(expected, actual, "Loaded IDF map should match expected values");
    }

    /**
     * Verifies that malformed lines in the IDF file are ignored while valid lines are loaded.
     */
    @Test
    public void testMalformedIdfLines() {
        IdfLoader loader = new IdfLoader();

        String malformedPath = System.getProperty("user.dir") 
                + File.separator + "testDocuments" 
                + File.separator + "idf_training" 
                + File.separator + "malformedIdf.txt";

        Map<String, Double> result = loader.loadMap(malformedPath);

        assertTrue(result.containsKey("valid"), "Should include valid key");
        assertFalse(result.containsKey("badline"), "Should skip line missing delimiter/value");
        assertFalse(result.containsKey("numberfail"), "Should skip line with unparseable double value");
        assertFalse(result.containsKey("extra"), "Should skip line with extra split tokens");
    }

    /**
     * Verifies that loading from a non-existent file returns an empty map instead of throwing an exception.
     */
    @Test
    public void testMissingIdfFile() {
        IdfLoader loader = new IdfLoader();

        String missingPath = System.getProperty("user.dir") 
                + File.separator + "testDocuments" 
                + File.separator + "idf_training" 
                + File.separator + "does_not_exist.txt";

        Map<String, Double> result = loader.loadMap(missingPath);

        assertNotNull(result, "Resulting map should not be null for missing files");
        assertTrue(result.isEmpty(), "Resulting map should be empty for missing files");
    }
}