package capstone.documenttaggingsystem;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.*;

public class IdfLoaderTest {

    /**
     * Loads the test Idf Map generated by the generateTestIdfMapFile() method
     * in IdfTrainerTest, then verifies that the loaded version equals the expected
     * version.
     */
    @Test
    public void testLoadingIdfMap(){
        IdfLoader idfLoader = new IdfLoader();

        Map<String, Double> expected = TestUtils.generateIdfMap();

        Map<String, Double> actual = idfLoader.loadMap(System.getProperty("user.dir") + "\\idfMaps\\testIdfMap.txt");

        Assertions.assertEquals(expected, actual);
    }
    /**
     * Verifies that malformed lines in the IDF file are ignored.
     */
    @Test
    public void testMalformedIdfLines() {
        IdfLoader loader = new IdfLoader();

        // Points to malformed file created
        Map<String, Double> result = loader.loadMap(
                System.getProperty("user.dir") + "/testDocuments/idf_training/malformedIdf.txt"
        );

        // Should only include valid lines like: valid,1.5
        assert(result.containsKey("valid"));
        assertFalse(result.containsKey("badline"));
        assertFalse(result.containsKey("numberfail"));
        assertFalse(result.containsKey("extra"));
    }

    // Verifies that loading from a non-existent file returns an empty map.
    @Test
    public void testMissingIdfFile() {
        IdfLoader loader = new IdfLoader();

        Map<String, Double> result = loader.loadMap(
                System.getProperty("user.dir") + "/testDocuments/idf_training/does_not_exist.txt"
        );

        assertNotNull(result);
        assertTrue(result.isEmpty());
    }
}
